#pragma once

#define THREAD_MAX_TITLE 50
#define THREAD_MIN_TITLE 3
#define THREAD_MAX_REPLIES 120

#define THREAD_TILE_DISPLAY_MAX 40
#define THREADS_TO_DISPLAY_PER_BOARD 30
#define THREAD_MAX_LINE_LENGTH 78
#define BOARD_MAX_NAME 32
#define AUTHOR_MAX_NAME 32
#define AUTHOR_MIN_NAME 3

#define LABEL_MAX_SIZE 120
#define LINE_INPUT_MAX_SIZE 120

#define REPLY_MAX_SIZE 1024
#define REPLY_MIN_SIZE 3

#define NICKNAME_MAX_SIZE 25

#define DEFAUL_USERNAME L"pagan"

#define MAX_PATH_LENGTH 255

#define BOARDS_NUMBER 5
enum Boards {
  BOARD_HIGHWAY,
  BOARD_MEATSPACE,
  BOARD_RANDOM,
  BOARD_TECHNOLOGY,
  BOARD_META,
};

#define ARCHIVE_ANALOG_DIRECTORY L"archive/analogcity"
#define ARCHIVE_PHRACK_DIRECTORY L"archive/phrack"
